name: Build

on:
  push:
    branches: [ more-tests ]
  pull_request:
    branches: [ more-tests ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install pytest-cov
    - name: Test with pytest
      run: |
        pytest --cov=fedot -s test/unit